### ISSUE TITLE
bug: TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by abhitrueprogrammer** [iqbal-rashed/pdftoimg-js#3]
When I run this the pdfToImage function with appropriate arguments, I get the following error: 

` ⨯ TypeError: Cannot read properties of undefined (reading 'prototype')
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/lib/bindings.js:7:20)
    at (rsc)/./node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/lib/bindings.j s(/.next/server/vendor-chunks/canvas@2.11.2.js:41:1)
    at __webpack_require__ (./.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/lib/canvas.js:9:18)
    at (rsc)/./node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/lib/canvas.js (.next/server/vendor-chunks/canvas@2.11.2.js:52:1)
    at __webpack_require__ (.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/index.js:1:16)
    at (rsc)/./node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/index.js (.next/server/vendor-chunks/canvas@2.11.2.js:19:1)
    at __webpack_require__ (./.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/pdftoimg-js@0.0.2/node_modules/pdftoimg-js/lib/node/utils.js:18:34)
    at (rsc)/./node_modules/.pnpm/pdftoimg-js@0.0.2/node_modules/pdftoimg-js/lib/node/utils.js (./.next/server/vendor-chunks/pdftoimg-js@0.0.2.js:30:1)
    at __webpack_require__ (./.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/pdftoimg-js@0.0.2/node_modules/pdftoimg-js/lib/node/index.js:40:17)
    at (rsc)/./node_modules/.pnpm/pdftoimg-js@0.0.2/node_modules/pdftoimg-js/lib/node/index.js (./.next/server/vendor-chunks/pdftoimg-js@0.0.2.js:20:1)
    at __webpack_require__ (./.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./src/util/mistral.ts:9:69)
    at (rsc)/./src/util/mistral.ts (./.next/server/app/api/ai-upload/route.js:252:1)
    at __webpack_require__ (./.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./src/app/api/ai-upload/route.ts:13:71)
    at (rsc)/./src/app/api/ai-upload/route.ts (./.next/server/app/api/ai-upload/route.js:212:1)
    at __webpack_require__ (./.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/next@14.2.22_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapi%2Fai-upload%2Froute&page=%2Fapi%2Fai-upload%2Froute&appPaths=&pagePath=private-next-app-dir%2Fapi%2Fai-upload%2Froute.ts&appDir=%2Fhome%2Fabhitruechamp%2Fgit%2Fpapers-codechef%2Fsrc%2Fapp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=%2Fhome%2Fabhitruechamp%2Fgit%2Fpapers-codechef&isDev=true&tsconfigPath=tsconfig.json&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!:15:128)
    at (rsc)/./node_modules/.pnpm/next@14.2.22_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapi%2Fai-upload%2Froute&page=%2Fapi%2Fai-upload%2Froute&appPaths=&pagePath=private-next-app-dir%2Fapi%2Fai-upload%2Froute.ts&appDir=%2Fhome%2Fabhitruechamp%2Fgit%2Fpapers-codechef%2Fsrc%2Fapp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=%2Fhome%2Fabhitruechamp%2Fgit%2Fpapers-codechef&isDev=true&tsconfigPath=tsconfig.json&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D! (./.next/server/app/api/ai-upload/route.js:192:1)
    at __webpack_require__ (./.next/server/webpack-runtime.js:33:43)
    at __webpack_exec__ (./.next/server/app/api/ai-upload/route.js:262:39)
    at ./.next/server/app/api/ai-upload/route.js:263:1411
    at __webpack_require__.X (./.next/server/webpack-runtime.js:168:21)
    at ./.next/server/app/api/ai-upload/route.js:263:47
    at Object.<anonymous> (./.next/server/app/api/ai-upload/route.js:266:3)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at mod.require (./node_modules/.pnpm/next@14.2.22_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at requirePage (./node_modules/.pnpm/next@14.2.22_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/require.js:109:84)
    at ./node_modules/.pnpm/next@14.2.22_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/load-components.js:103:84
    at async loadComponentsImpl (./node_modules/.pnpm/next@14.2.22_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/load-components.js:103:26)
    at async DevServer.findPageComponentsImpl (./node_modules/.pnpm/next@14.2.22_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:714:36)
    at async DevServer.findPageComponents (./node_modules/.pnpm/next@14.2.22_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/dev/next-dev-server.js:577:20)
    at async DevServer.renderPageComponent (./node_modules/.pnpm/next@14.2.22_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1897:24)
    at async DevServer.renderToResponseImpl (./node_modules/.pnpm/next@14.2.22_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1949:32)
    at async DevServer.pipeImpl (./node_modules/.pnpm/next@14.2.22_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:921:25)
    at async NextNodeServer.handleCatchallRenderRequest (./node_modules/.pnpm/next@14.2.22_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (./node_modules/.pnpm/next@14.2.22_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:817:17)
    at async ./node_modules/.pnpm/next@14.2.22_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (./node_modules/.pnpm/next@14.2.22_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (./node_modules/.pnpm/next@14.2.22_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (./node_modules/.pnpm/next@14.2.22_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:173:21) {`

**Comment by iqbal-rashed** [comment]
Try latest version 0.2.2
